<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Contact Form Submission</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            color: #333; 
            background-color: #f9f9f9;
            margin: 0;
            padding: 20px;
        }
        .container { 
            max-width: 600px; 
            margin: 0 auto; 
            background: white;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header { 
            background: linear-gradient(135deg, #10b981, #059669);
            color: white; 
            padding: 30px 20px; 
            text-align: center; 
        }
        .header h1 { 
            margin: 0; 
            font-size: 24px;
            font-weight: 600;
        }
        .content { 
            padding: 30px; 
        }
        .field-group { 
            margin-bottom: 20px; 
            padding: 15px;
            background: #f8fafc;
            border-radius: 8px;
            border-left: 4px solid #10b981;
        }
        .label { 
            font-weight: 600; 
            color: #10b981;
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .value { 
            color: #374151; 
            font-size: 16px;
            line-height: 1.5;
        }
        .message-content {
            background: white;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 15px;
            margin-top: 8px;
            white-space: pre-wrap;
            font-family: inherit;
        }
        .footer { 
            text-align: center; 
            padding: 20px; 
            background: #f8fafc;
            color: #6b7280;
            font-size: 12px;
            border-top: 1px solid #e5e7eb;
        }
        .highlight {
            background: #fffbeb;
            border: 1px solid #fcd34d;
            border-radius: 6px;
            padding: 15px;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📧 New Contact Form Submission</h1>
        </div>
        
        <div class="content">
            <div class="highlight">
                <strong>You have received a new message through the ServeDavao contact form.</strong>
            </div>

            <div class="field-group">
                <span class="label">Full Name</span>
                <div class="value">{{ $fullName }}</div>
            </div>

            <div class="field-group">
                <span class="label">Email Address</span>
                <div class="value">
                    <a href="mailto:{{ $email }}" style="color: #10b981; text-decoration: none;">
                        {{ $email }}
                    </a>
                </div>
            </div>

            <div class="field-group">
                <span class="label">Subject</span>
                <div class="value">
                    <strong>{{ $subjectLabel }}</strong>
                    @if ($subject !== $subjectLabel)
                        <br><small style="color: #6b7280;">Internal: {{ $subject }}</small>
                    @endif
                </div>
            </div>

            <div class="field-group">
                <span class="label">Message</span>
                <div class="message-content">{{ $contactMessage }}</div>
            </div>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-top: 25px;">
                <div style="background: #f0fdf4; padding: 12px; border-radius: 6px; border-left: 4px solid #10b981;">
                    <div style="font-size: 12px; color: #065f46; font-weight: 600;">IP ADDRESS</div>
                    <div style="font-size: 14px; color: #047857;">{{ $ipAddress }}</div>
                </div>
                <div style="background: #f0f9ff; padding: 12px; border-radius: 6px; border-left: 4px solid #0ea5e9;">
                    <div style="font-size: 12px; color: #075985; font-weight: 600;">RECEIVED</div>
                    <div style="font-size: 14px; color: #0369a1;">{{ $timestamp }}</div>
                </div>
            </div>
        </div>
        
        <div class="footer">
            <p>This email was automatically generated by the ServeDavao contact form.</p>
            <p>&copy; {{ date('Y') }} ServeDavao. All rights reserved.</p>
        </div>
    </div>
</body>
</html>